### ISSUE TITLE
请问作者这个软件提取分数的原理是啥呀？

### ISSUE THREAD

**Issue by firesky123** [beikwx/SailVina#2]
请问作者这个软件提取分数的原理是啥呀，自己以前写过一个正则表达，在vina1.1.2的情况下还算能工作，把匹配到的第一个分数拿出来和再把我配体受体的名字同时输入excel，但是在vina1.2.3计算出来的结果就不太适用了。今天尝试了下sailvina的提取分数功能发现还不错，但就是还得自己手动把配体受体名字输入excel，所以想请教下作者这里面提取分数的原理是啥，或者在哪一个脚本里，可以我学习一下，万分感谢。

**Comment by beikwx** [comment]
只是通过读取生成的文件里面的信息，配体受体名字是根据文件夹的名字来命名的。代码可以见read_scores.py。

**Comment by firesky123** [comment]
好呢，感谢，我研究一下。
