### ISSUE TITLE
关于SailVina准备配体部分的疑问

### ISSUE THREAD

**Issue by Aswau** [beikwx/SailVina#3]
您好，请问SailVina准备配体有设置加氢、检测扭转中心和扭转角吗？谢谢。

**Comment by beikwx** [comment]
是使用Open Babel和AutodockTools里面的prepligand4来准备配体。可以根据pH加氢，最终的配体是经过能量最小化处理，并且应该是自动设置了扭转中心和扭转角。

**Comment by Aswau** [comment]
谢谢您的回复！
不过不知道为啥，完全使用SailVina准备的配体和我用同样流程手动准备的配体，各个原子的位置还是略有差异，但如果先手动准备至MMFF94能量最小化，再使用SailVina转成pdbqt格式，这样得到的配体各原子位置就一致了。
另外还想请教一下您，无论是纯手动准备的配体还是SailVina准备的配体，对接结果都可能会出现一些配体的结构会碎裂的现象。对此，猜测可能是能量最小化的原因，换了Chem3D能量优化后会有所好转，但对接得到的结合能也会发生较大变化……请问一下这种情况有什么比较合适的处理办法吗？
万望赐教。



在 2022-11-19 16:09:42，"beikwx" ***@***.***> 写道：

是使用Open Babel和AutodockTools里面的prepligand4来准备配体。可以根据pH加氢，最终的配体是经过能量最小化处理，并且应该是自动设置了扭转中心和扭转角。

**Comment by beikwx** [comment]
配体是先通过opbabel转pdb，再通过autodock自带的程序转pdbqt的，所以如果你手动到pdb，后面的结果就是一致的。openbabel在对一些结构的处理上是存在一定的问题的，所以会出现你说的现象。对于一些格式你首先自行判断需要的方法，当基本不会出现问题的时候再进行虚拟筛选。

**Comment by Aswau** [comment]
谢谢赐教！



在 2022-11-20 17:10:39，"beikwx" ***@***.***> 写道：

配体是先通过opbabel转pdb，再通过autodock自带的程序转pdbqt的，所以如果你手动到pdb，后面的结果就是一致的。openbabel在对一些结构的处理上是存在一定的问题的，所以会出现你说的现象。对于一些格式你首先自行判断需要的方法，当基本不会出现问题的时候再进行虚拟筛选。
