### ISSUE TITLE
脚本配置提示路径错误

### ISSUE THREAD

**Issue by wwl5600** [beikwx/SailVina#4]
选择完ADT的python路径（里面也没有空格和中文），但一直提示“”请确定选择的是安装adt软性的python.exe!”
![111111](https://github.com/beikwx/SailVina/assets/91039618/9bf30a6c-1107-4a6d-ac6f-aa14c1bbf2ce)

**Comment by beikwx** [comment]
暂时不知道原因，可以邮件联系我。
