### ISSUE TITLE
第一步获取pdb结构错误：无法检测状态，请检查网络或者id是否正确！

### ISSUE THREAD

**Issue by logseq20182018** [beikwx/SailVina#5]
![image](https://github.com/beikwx/SailVina/assets/72118514/f1db775b-340c-408f-993c-11d28f285aef)

**Comment by beikwx** [comment]
这个功能目前已经无法使用，因为官方之后修改了下载的网页。请手动下载pdb文件。

**Comment by 13623618422** [comment]
能修改获取网址不？或者给个输入口，我们自己根据官网随时调整
