### ISSUE TITLE
配体准备出错

### ISSUE THREAD

**Issue by yunpengyang** [beikwx/SailVina#6]
您好，我现在希望使用您的软件进行分子批量对接。我在ZINC库中下载了smiles格式的配体，因为看到您的软件输入格式中没有这个选项，因此自己使用OPENBABEL进行小分子的文件转换，将.smi转换为.mol和.sdf。希望使用这个软件。但是我转换为这两个格式后，均不能成功完成软件中的准备配体部分。请问问题出在哪里呢？您的代码中要求的配体格式要求是什么呢？期望得到您的回复，万分感谢。

**Comment by beikwx** [comment]
mol和sdf都是支持的，有日志吗？不好确认问题。

**Comment by LutherScript** [comment]
sdf和mol格式的配体都不能转换，报错原因 C:\MDOCK\Ligand\Conformer3D_COMPOUND_CID_5388906.pdbqt准备失败，可能文件内部格式有误 ，没有选择3D选项；这个配体是从pubchem下载的用mgtools处理的话就可以对接。

另外还有其他问题，在转换过程中会要求选择软件打开sdf文件，选择后还会出现第二次选择打开处理lignad的python脚本

**Comment by beikwx** [comment]
格式转换是调用openbabal的转换，就是扩展名是一样的，但是内部不是标准格式可能无法转换，只能手动准备了。
