### ISSUE TITLE
关于生成复合物

### ISSUE THREAD

**Issue by gibhdyw** [beikwx/SailVina#7]
首先非常感谢作者无偿的分享，我想问下对于生成复合物这步，选择的配体可以选择sdf文件时预处理后的还直接可以放进去，另外蛋白的格式也需要是预处理后的pdbqt格式吗？不可是其他软件如薛定谔处理后的pdb文件吗？

**Comment by beikwx** [comment]
生成复合物就是调用openbabel的结合方法。选择对应的配体和受体，只要格式正确即可。可以将pdb文件转为pdbqt再复合。
